---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  annotations:
    cert-manager.io/cluster-issuer: production
spec:
  ingressClassName: external-nginx
  rules:
    - host: systemofbizkitkornpark.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: blog-nginx-service
                port:
                  number: 8080
  tls:
    - hosts:
        - systemofbizkitkornpark.com
      secretName: systemofbizkitkornpark-com